name: Docker

on: push

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: circleci-ruby25-aws-cli

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    container:
      image: ruby:3.0.1
      options: --user 1001

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: touch hoge

      - name: aa
        run: pwd

      - name: bb
        run: ls -la

      - name: hoge
        run: whoami

