name: Docker

on: push

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: circleci-ruby25-aws-cli

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    container:
      image: ruby:3.0.1
      env:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        RAILS_ENV: test
        RACK_ENV: test
        BUNDLE_PATH: vendor/bundle

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - run: gem install bundler

      - run: ls -la 

      - run: bundle check || bundle install

