name: Docker

on: push

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: circleci-ruby25-aws-cli

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    container:
      image: ruby:3.0.1

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: fuga
          key: fuga

      - name: Build image
        run: mkdir fuga && touch fuga/hoge

      - name: aa
        run: pwd

      - name: bb
        run: ls -la

